using System.Text;

namespace ProtoBufferParser.Services;

/// <summary>
/// Generates the auto-generated file comment header for output files.
/// </summary>
public sealed class FileHeaderTemplate
{
    /// <summary>
    /// Generates the standard auto-generated comment block.
    /// </summary>
    /// <param name="sourceProtoFile">The source .proto file name.</param>
    /// <returns>The comment block string.</returns>
    public string Generate(string sourceProtoFile)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// ----------------------------------------------");
        sb.AppendLine($"// AUTO-GENERATED from {sourceProtoFile}");
        sb.AppendLine("// DO NOT MODIFY - Changes will be overwritten");
        sb.AppendLine("// Generated by ProtoBufferParser");
        sb.AppendLine("// ----------------------------------------------");
        return sb.ToString();
    }
}
