using ProtoBufferParser.Services;

namespace ProtoBufferParser.Tests.Services;

public sealed class FileHeaderTemplateTests
{
    private readonly FileHeaderTemplate _template = new();

    [Fact]
    public void Generate_ContainsSourceFileName()
    {
        var result = _template.Generate("player.proto");

        Assert.Contains("player.proto", result);
    }

    [Fact]
    public void Generate_ContainsAutoGeneratedComment()
    {
        var result = _template.Generate("test.proto");

        Assert.Contains("AUTO-GENERATED", result);
        Assert.Contains("DO NOT MODIFY", result);
        Assert.Contains("ProtoBufferParser", result);
    }

    [Fact]
    public void Generate_ContainsSeparatorLines()
    {
        var result = _template.Generate("test.proto");

        Assert.Contains("// ------", result);
    }
}
