using ProtoBufferParser.Models;
using ProtoBufferParser.Services;
using ProtoBufferParser.Tests.Helpers;

namespace ProtoBufferParser.Tests.Services;

public sealed class UnrealCodeGeneratorTests
{
    private readonly UnrealTypeMapper _typeMapper = new();
    private readonly MockLogger _logger = new();

    private UnrealCodeGenerator CreateGenerator() =>
        new(_typeMapper, _logger);

    private static ProtoFileNode CreateSimpleProtoFile()
    {
        return new ProtoFileNode
        {
            FileName = "player.proto",
            Package = "game",
            Imports = new List<ImportNode>(),
            Messages = new List<MessageNode>
            {
                new()
                {
                    Name = "Player",
                    FullName = "Player",
                    ProtocTypeName = "Player",
                    Fields = new List<FieldNode>
                    {
                        new() { Name = "id", Type = "int32", FieldNumber = 1 },
                        new() { Name = "name", Type = "string", FieldNumber = 2 }
                    }
                }
            },
            Enums = new List<EnumNode>()
        };
    }

    // ========== Basic Generation ==========

    [Fact]
    public void Generate_SimpleMessage_ReturnsOneType()
    {
        var generator = CreateGenerator();
        var ast = CreateSimpleProtoFile();

        var result = generator.Generate(ast);

        Assert.Single(result.Types);
        Assert.Equal("FPlayerProto", result.Types[0].TypeName);
    }

    [Fact]
    public void Generate_SimpleMessage_GeneratesHeaderFile()
    {
        var generator = CreateGenerator();
        var ast = CreateSimpleProtoFile();

        var result = generator.Generate(ast);

        Assert.Equal("MEPlayerProto.h", result.Types[0].HeaderFile.FileName);
        Assert.Contains("struct FPlayerProto", result.Types[0].HeaderFile.Content);
    }

    [Fact]
    public void Generate_SimpleMessage_GeneratesCppFile()
    {
        var generator = CreateGenerator();
        var ast = CreateSimpleProtoFile();

        var result = generator.Generate(ast);

        Assert.NotNull(result.Types[0].CppFile);
        Assert.Equal("MEPlayerProto.cpp", result.Types[0].CppFile!.FileName);
        Assert.Contains("FPlayerProto::FPlayerProto(const game::Player& proto)", result.Types[0].CppFile!.Content);
    }

    [Fact]
    public void Generate_SimpleMessage_HeaderContainsAutoGeneratedComment()
    {
        var generator = CreateGenerator();
        var ast = CreateSimpleProtoFile();

        var result = generator.Generate(ast);

        Assert.Contains("AUTO-GENERATED from player.proto", result.Types[0].HeaderFile.Content);
    }

    [Fact]
    public void Generate_SimpleMessage_CppContainsAutoGeneratedComment()
    {
        var generator = CreateGenerator();
        var ast = CreateSimpleProtoFile();

        var result = generator.Generate(ast);

        Assert.Contains("AUTO-GENERATED from player.proto", result.Types[0].CppFile!.Content);
    }

    // ========== Enum Generation ==========

    [Fact]
    public void Generate_EnumOnly_ReturnsEnumType()
    {
        var generator = CreateGenerator();
        var ast = new ProtoFileNode
        {
            FileName = "status.proto",
            Imports = new List<ImportNode>(),
            Messages = new List<MessageNode>(),
            Enums = new List<EnumNode>
            {
                new()
                {
                    Name = "Status",
                    FullName = "Status",
                    Values = new List<EnumValueNode>
                    {
                        new() { Name = "UNKNOWN", Value = 0 },
                        new() { Name = "ACTIVE", Value = 1 }
                    }
                }
            }
        };

        var result = generator.Generate(ast);

        Assert.Single(result.Types);
        Assert.Equal("EStatusProto", result.Types[0].TypeName);
        Assert.Equal("MEStatusProto.h", result.Types[0].HeaderFile.FileName);
        Assert.Contains("enum class EStatusProto : uint8", result.Types[0].HeaderFile.Content);
    }

    [Fact]
    public void Generate_EnumOnly_NoCppFile()
    {
        var generator = CreateGenerator();
        var ast = new ProtoFileNode
        {
            FileName = "status.proto",
            Imports = new List<ImportNode>(),
            Messages = new List<MessageNode>(),
            Enums = new List<EnumNode>
            {
                new()
                {
                    Name = "Status",
                    FullName = "Status",
                    Values = new List<EnumValueNode>
                    {
                        new() { Name = "UNKNOWN", Value = 0 }
                    }
                }
            }
        };

        var result = generator.Generate(ast);

        Assert.Null(result.Types[0].CppFile);
    }

    // ========== Mixed Messages and Enums ==========

    [Fact]
    public void Generate_MixedMessagesAndEnums_ReturnsAll()
    {
        var generator = CreateGenerator();
        var ast = new ProtoFileNode
        {
            FileName = "game.proto",
            Imports = new List<ImportNode>(),
            Messages = new List<MessageNode>
            {
                new()
                {
                    Name = "Player",
                    FullName = "Player",
                    ProtocTypeName = "Player",
                    Fields = new List<FieldNode>
                    {
                        new() { Name = "id", Type = "int32", FieldNumber = 1 }
                    }
                },
                new()
                {
                    Name = "Item",
                    FullName = "Item",
                    ProtocTypeName = "Item",
                    Fields = new List<FieldNode>
                    {
                        new() { Name = "name", Type = "string", FieldNumber = 1 }
                    }
                }
            },
            Enums = new List<EnumNode>
            {
                new()
                {
                    Name = "Status",
                    FullName = "Status",
                    Values = new List<EnumValueNode>
                    {
                        new() { Name = "UNKNOWN", Value = 0 }
                    }
                }
            }
        };

        var result = generator.Generate(ast);

        // Enums come first, then messages
        Assert.Equal(3, result.Types.Count);
        Assert.Equal("EStatusProto", result.Types[0].TypeName);
        Assert.Equal("FPlayerProto", result.Types[1].TypeName);
        Assert.Equal("FItemProto", result.Types[2].TypeName);
    }

    // ========== AllFiles Property ==========

    [Fact]
    public void Generate_AllFiles_FlattensProperly()
    {
        var generator = CreateGenerator();
        var ast = new ProtoFileNode
        {
            FileName = "game.proto",
            Imports = new List<ImportNode>(),
            Messages = new List<MessageNode>
            {
                new()
                {
                    Name = "Player",
                    FullName = "Player",
                    ProtocTypeName = "Player",
                    Fields = new List<FieldNode>
                    {
                        new() { Name = "id", Type = "int32", FieldNumber = 1 }
                    }
                }
            },
            Enums = new List<EnumNode>
            {
                new()
                {
                    Name = "Status",
                    FullName = "Status",
                    Values = new List<EnumValueNode>
                    {
                        new() { Name = "UNKNOWN", Value = 0 }
                    }
                }
            }
        };

        var result = generator.Generate(ast);
        var allFiles = result.AllFiles.ToList();

        // Enum: 1 header only (no cpp), Message: 1 header + 1 cpp = 3 total
        Assert.Equal(3, allFiles.Count);
        Assert.Contains(allFiles, f => f.FileName == "MEStatusProto.h");
        Assert.Contains(allFiles, f => f.FileName == "MEPlayerProto.h");
        Assert.Contains(allFiles, f => f.FileName == "MEPlayerProto.cpp");
    }

    // ========== Dependencies ==========

    [Fact]
    public void Generate_MessageWithImports_NoFieldUsage_NoImportIncludes()
    {
        var generator = CreateGenerator();
        var ast = new ProtoFileNode
        {
            FileName = "game.proto",
            Imports = new List<ImportNode>
            {
                new() { Path = "common.proto" }
            },
            Messages = new List<MessageNode>
            {
                new()
                {
                    Name = "Player",
                    FullName = "Player",
                    ProtocTypeName = "Player",
                    Fields = new List<FieldNode>
                    {
                        new() { Name = "id", Type = "int32", FieldNumber = 1 }
                    }
                }
            },
            Enums = new List<EnumNode>()
        };

        var result = generator.Generate(ast);

        // Import exists but Player doesn't use any type from common.proto,
        // so no import-based include should be generated.
        Assert.DoesNotContain("#include \"MECommonProto.h\"", result.Types[0].HeaderFile.Content);
    }

    [Fact]
    public void Generate_MessageWithFieldDependency_HeaderContainsDependencyInclude()
    {
        var generator = CreateGenerator();
        var ast = new ProtoFileNode
        {
            FileName = "game.proto",
            Imports = new List<ImportNode>(),
            Messages = new List<MessageNode>
            {
                new()
                {
                    Name = "GameSession",
                    FullName = "GameSession",
                    ProtocTypeName = "GameSession",
                    Fields = new List<FieldNode>
                    {
                        new() { Name = "host", Type = "Player", FieldNumber = 1 }
                    }
                }
            },
            Enums = new List<EnumNode>()
        };

        var result = generator.Generate(ast);

        Assert.Contains("#include \"MEPlayerProto.h\"", result.Types[0].HeaderFile.Content);
    }

    // ========== Logging ==========

    [Fact]
    public void Generate_LogsInfoMessages()
    {
        var generator = CreateGenerator();
        var ast = CreateSimpleProtoFile();

        generator.Generate(ast);

        Assert.NotEmpty(_logger.InfoMessages);
        Assert.Contains(_logger.InfoMessages, m => m.Contains("player.proto"));
    }

    [Fact]
    public void Generate_LogsVerboseForEachType()
    {
        var generator = CreateGenerator();
        var ast = CreateSimpleProtoFile();

        generator.Generate(ast);

        Assert.NotEmpty(_logger.VerboseMessages);
        Assert.Contains(_logger.VerboseMessages, m => m.Contains("FPlayerProto"));
    }

    // ========== Null Checks ==========

    [Fact]
    public void Generate_NullAst_ThrowsArgumentNullException()
    {
        var generator = CreateGenerator();

        Assert.Throws<ArgumentNullException>(() => generator.Generate(null!));
    }

    [Fact]
    public void Constructor_NullTypeMapper_ThrowsArgumentNullException()
    {
        Assert.Throws<ArgumentNullException>(() =>
            new UnrealCodeGenerator(null!, _logger));
    }

    [Fact]
    public void Constructor_NullLogger_ThrowsArgumentNullException()
    {
        Assert.Throws<ArgumentNullException>(() =>
            new UnrealCodeGenerator(_typeMapper, null!));
    }

    // ========== Empty Proto File ==========

    [Fact]
    public void Generate_EmptyProtoFile_ReturnsEmptyResult()
    {
        var generator = CreateGenerator();
        var ast = new ProtoFileNode
        {
            FileName = "empty.proto",
            Imports = new List<ImportNode>(),
            Messages = new List<MessageNode>(),
            Enums = new List<EnumNode>()
        };

        var result = generator.Generate(ast);

        Assert.Empty(result.Types);
    }

    // ========== End-to-End: Full header content structure ==========

    [Fact]
    public void Generate_VerifyFullHeaderStructure()
    {
        var generator = CreateGenerator();
        var ast = CreateSimpleProtoFile();

        var result = generator.Generate(ast);
        var header = result.Types[0].HeaderFile.Content;

        // Verify order: comment → pragma → includes → USTRUCT → struct → fields
        var commentIdx = header.IndexOf("AUTO-GENERATED");
        var pragmaIdx = header.IndexOf("#pragma once");
        var coreMinimalIdx = header.IndexOf("#include \"CoreMinimal.h\"");
        var generatedIdx = header.IndexOf(".generated.h\"");
        var ustructIdx = header.IndexOf("USTRUCT(BlueprintType)");
        var structIdx = header.IndexOf("struct FPlayerProto");

        Assert.True(commentIdx < pragmaIdx, "Comment should come before #pragma once");
        Assert.True(pragmaIdx < coreMinimalIdx, "#pragma once should come before CoreMinimal");
        Assert.True(coreMinimalIdx < generatedIdx, "CoreMinimal should come before .generated.h");
        Assert.True(generatedIdx < ustructIdx, ".generated.h should come before USTRUCT");
        Assert.True(ustructIdx < structIdx, "USTRUCT should come before struct definition");
    }

    // ========== End-to-End: Full cpp content structure ==========

    [Fact]
    public void Generate_VerifyFullCppStructure()
    {
        var generator = CreateGenerator();
        var ast = CreateSimpleProtoFile();

        var result = generator.Generate(ast);
        var cpp = result.Types[0].CppFile!.Content;

        // Verify order: comment → self-include → pb.h include → constructor
        var commentIdx = cpp.IndexOf("AUTO-GENERATED");
        var selfIncludeIdx = cpp.IndexOf("#include \"MEPlayerProto.h\"");
        var pbIncludeIdx = cpp.IndexOf("#include \"player.pb.h\"");
        var constructorIdx = cpp.IndexOf("FPlayerProto::FPlayerProto");

        Assert.True(commentIdx < selfIncludeIdx, "Comment should come before self-include");
        Assert.True(selfIncludeIdx < pbIncludeIdx, "Self-include should come before .pb.h include");
        Assert.True(pbIncludeIdx < constructorIdx, ".pb.h include should come before constructor");
    }
}
